export { ChartExportOptions, EnergyChart, ExportFormat, GapChart, GearChart, LapComparisonChart, MiniSectors, PitStopTimeline, PositionChart, RadarChart, SpeedChart, SpeedHeatmapTrackMap, TelemetryContextValue, TelemetryDashboard, TelemetryPlayground, TelemetryPlaygroundProps, TelemetryProvider, TelemetryProviderProps, ThrottleBrakeChart, TrackMap, TyreStrategyTimeline, UseChartExportResult, UseCursorSyncResult, UseTelemetryOptions, UseTelemetryResult, WeatherWidget, createLineAnnotationDatasets, createTelemetryCssVariables, createTrackAnnotationDataset, createTrackAnnotationDatasets, telemetryCssVariables, useAutoTheme, useChartExport, useCursorSync, useTelemetry, useTelemetryContext } from './react.js';
export { DRSZone, F1Driver, F1Team, F1Track, F1_DRIVERS, F1_TEAMS, FLAG_TYPES, FlagType, RACE_CALENDAR_2025, RACE_COMPOUND_ALLOCATIONS, RaceCompoundAllocation, RaceWeekend, TEAM_COLORS, TRACKS, TYRE_COMPOUNDS, TyreCompoundInfo, classifyTyreCompound, computeLapTimes, computeSectorTimes, computeSpeedDelta, computeTimeDelta, detectOvertakes, exportToCsv, exportToJson, formatTelemetry, getDriver, getDriverColor, getFlag, getNextRace, getRaceByRound, getRaceCompounds, getSprintWeekends, getTeam, getTeamDrivers, getTrack, getTrackIds, getTyreColor, interpolateTelemetry, mergeTelemetry, normalizeDistance, normalizeTelemetryTime, validateTelemetry } from './core.js';
export { findNearestIndex, processSeriesData, processSeriesDataInWorker } from './performance.js';
export { TELEMETRY_EXTENSION_API_VERSION, VersionedTelemetryPanelExtension, assertTelemetryExtensionCompatible, clearTelemetryPanels, gearDistributionPanel, getTelemetryPanels, lapSummaryPanel, normalizeTelemetryPanelExtension, overtakeTimelinePanel, registerTelemetryPanel, sectorPaceEvolutionPanel, stintDegradationPanel, telemetryStatsPanel, unregisterTelemetryPanel } from './extensions.js';
export { CsvTelemetryOptions, ErgastParsedData, ErgastRaceData, FastF1TelemetryInput, FastF1TelemetryPoint, JsonFieldMapping, JsonTelemetryOptions, MultiViewerCarData, MultiViewerParsedTiming, MultiViewerSessionData, MultiViewerTimingData, OpenF1DriverInfo, OpenF1FetchOptions, OpenF1FetchTelemetryOptions, OpenF1SessionInfo, OpenF1TelemetryPoint, ParquetTelemetryOptions, ParsedLapTimes, ParsedRaceResult, fetchOpenF1Drivers, fetchOpenF1Sessions, fetchOpenF1Telemetry, fetchOpenF1TelemetryWithDiagnostics, fromCsvTelemetry, fromCsvTelemetryWithDiagnostics, fromErgastApi, fromFastF1Telemetry, fromFastF1TelemetryWithDiagnostics, fromJsonTelemetry, fromJsonTelemetryWithDiagnostics, fromMultiViewerCarData, fromMultiViewerCarDataWithDiagnostics, fromMultiViewerTiming, fromOpenF1Telemetry, fromOpenF1TelemetryWithDiagnostics, fromParquet, fromParquetWithDiagnostics } from './adapters.js';
export { A as AdapterName, a as AdapterParseOptions, b as AdaptiveDownsampleOptions, c as AnnotationProps, C as ChartContainerProps, d as CsvExportOptions, e as CursorSyncProps, D as DataProcessingOptions, f as DeltaPoint, g as DistanceBasedTelemetry, h as DownsampleStrategy, i as DriverGapData, j as DriverLapTelemetry, k as DriverMetrics, l as DriverPitStops, m as DriverPositionData, n as DriverPositionHistory, o as DriverSectorData, p as DriverStrategy, E as EnergyChartProps, F as FormattedTelemetry, G as GapChartProps, q as GapDataPoint, r as GearChartProps, I as IssueSeverity, J as JsonExportFormat, L as LapComparisonChartProps, s as LapComparisonMode, t as LapSectors, u as LapTime, M as MiniSectorsProps, O as OvertakeEvent, P as PitStop, v as PitStopTimelineProps, w as PositionChartProps, R as RadarChartProps, x as RawTelemetryInput, y as RawTelemetryPoint, S as SectorComparison, z as SectorSplit, B as SectorTime, H as SpeedChartProps, K as SpeedHeatmapTrackMapProps, T as TelemetryAdapterDiagnostic, N as TelemetryAdapterDiagnostics, Q as TelemetryAdapterResult, U as TelemetryAnnotation, V as TelemetryAnnotationType, W as TelemetryChartType, X as TelemetryDashboardLayout, Y as TelemetryDashboardLayoutItem, Z as TelemetryDashboardProps, _ as TelemetryEvent, $ as TelemetryExtraChannel, a0 as TelemetryPanelContextMenuAction, a1 as TelemetryPanelExtension, a2 as TelemetryPanelRenderContext, a3 as TelemetrySeriesKey, a4 as TelemetrySeverity, a5 as TelemetrySharedChannelApi, a6 as TelemetryStyleTokens, a7 as TelemetryTimeReference, a8 as TelemetryValidationDiagnostics, a9 as TelemetryValidationIssue, aa as TelemetryValidationOptions, ab as TelemetryValidationResult, ac as TelemetryWindow, ad as ThemeMode, ae as ThrottleBrakeChartProps, af as TimeDeltaPoint, ag as TrackMapProps, ah as TyreClassification, ai as TyreCompound, aj as TyreStint, ak as TyreStrategyTimelineProps, al as ValidationMode, am as WeatherDataPoint, an as WeatherMetric, ao as WeatherWidgetProps } from './telemetry-CQTgwsmr.js';
import 'react/jsx-runtime';
import 'react';
import 'chart.js';
